spring.application.name=SentinelCore_Backend

# ---------- PostgreSQL ----------
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelcore_db
spring.datasource.username=postgres
spring.datasource.password=Nivetha@1288
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------- Redis (Disabled / Excluded) ----------
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.health.redis.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# ---------- Server ----------
server.port=8080

# ---------- Mail ----------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mynew222028@gmail.com
spring.mail.password=rjxx bslx wshd ypwd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ---------- Twilio SMS ----------
custom.twilio.sid=${TWILIO_SID:YOUR_TWILIO_SID_HERE}
custom.twilio.token=${TWILIO_TOKEN:YOUR_TWILIO_TOKEN_HERE}
custom.twilio.phone=+17372508034
twilio.to.phone.number=+919940232013
